### ISSUE TITLE
[Problem] Sketcher: Unable to select angular constraint lying on X-axis

### ISSUE THREAD

**Issue by chrisb-github** [FreeCAD/FreeCAD#12756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I am unable to select the angle constraint in 3D view, when it lies on the X-axis. I can see that always the axis itself is preselected.
![SnipScreenshot-c234ec](https://github.com/FreeCAD/FreeCAD/assets/11750017/4cbab2b6-e626-4c44-89e8-b2bb0d4441b3)

I can change the value of the constraint from the elements list, but I cannot change the position of the dimension. It seems that the X-axis is always selected first

On Y-axis I can select the constraint by moving the mouse from the side of the dimension.

### Full version info

```shell
OS: macOS 13.0
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36228 (Git)
Build type: Release
Branch: main
Hash: 6c8ee5964521a99e01c8d33cbf9aac8a19273ef3
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * FC_SU
  * freecad.gears 1.2.0
  * FeedsAndSpeeds 0.5.0
  * dxf-library
  * fasteners 0.5.13
  * sheetmetal 0.4.2
  * ExplodedAssembly
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Can confirm

**Comment by pierreporte** [comment]
@FlachyJoe A third possiblity is to consider that the whole dimension can be clicked to select it, not only the label.

**Comment by maxwxyz** [comment]
Could the dimension be rendered on top of axes?
If possible, 

1. geometry on top (would solve the overlay issues of dimension lines); dotted geo (construction, external over normal one to see dashs)
2. constraints
3. origin and axis cross

**Comment by FlachyJoe** [comment]
@pierreporte Selection works with bounding-box it can't be so huge.
@maxwxyz it's already the case:
![image](https://github.com/FreeCAD/FreeCAD/assets/10371513/06a8e252-0932-4b41-ba5d-2878bf499e54)
Blue angle constraint on top of red X axis.

In fact the problem seems more general: we can select easily any constraint at the bottom of the label but a blank zone exists on the upper part.
![Capture d’écran_2024-03-06_21-40-29](https://github.com/FreeCAD/FreeCAD/assets/10371513/0e7c04fc-c150-4391-a922-061f09b2b2ab)
Can someone confirm this issue?

**Comment by pierreporte** [comment]
@FlachyJoe For me the bounding box seems to be a rectangle.

```
OS: Ubuntu 23.10 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36166 (Git) AppImage
Build type: Release
Branch: main
Hash: a5ea8023a29b6d7bbf1ebd57b5ed31dd27c5947b
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: French/France (fr_FR)
Installed mods: 
  * CosmeticThread3D
  * TabBar (Disabled)
  * Curves 0.6.23
  * CurvedShapes 1.0.5
  * sheetmetal 0.4.0
  * OpenDark 2023.12.1
  * OpenLight 2023.12.17
```

Is the big bounding box easily avoidable? It would be an improvement to be able to select dimensions by clicking on the lines.

**Comment by FlachyJoe** [comment]
not pre-selected
![image](https://github.com/FreeCAD/FreeCAD/assets/10371513/8143416c-c674-44ca-8672-82b614677e37)
pre-selected
![image](https://github.com/FreeCAD/FreeCAD/assets/10371513/c5ebcb91-dda1-466d-ae4d-c99e5b5e6dde)

```
OS: Debian GNU/Linux trixie/sid (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36323 (Git)
Build type: Debug
Branch: main
Hash: bdf46e7337fef88f20d58b1d8bc01411d967498e
Python 3.11.8, Qt 5.15.10, Coin 4.0.2, Vtk 9.1.0, OCC 7.6.3
Locale: French/France (fr_FR)
```

**Comment by obelisk79** [comment]
The underlying issue that would address this and other selection problems throughout FreeCAD is to establish a selection priority system. We are able to set selection (pick) radius. But what FreeCAD fails to do, is prioritize elements based on what is within that radius. It seemingly stops at the first element it finds. In this case, I would presume, the axis is always the first thing found because of some code structuring.

**Comment by maxwxyz** [comment]
@obelisk79 https://github.com/FreeCAD/FreeCAD/issues/10308

**Comment by luzpaz** [comment]
bumping for visibility

**Comment by FlachyJoe** [comment]
I think this issue was fixed by #12797

**Comment by pierreporte** [comment]
I still have the problem while #12797 was merged 6 months ago. Only the selectable area was fixed.

```
OS: Ubuntu 24.04 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38642 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 1.0rc1)
Hash: 60a251354e203bdb924e2190fb9f5e18b48d7362
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: French/France (fr_FR)
Installed mods: 
  * CosmeticThread3D
  * Curves 0.6.39
  * CurvedShapes 1.0.9
  * sheetmetal 0.4.19
```

**Comment by luzpaz** [comment]
@pierreporte What's left to fix here specifically ?

**Comment by pierreporte** [comment]
@luzpaz The bounding box of the label is still the same height of the bounding box of the X axis. Only the shape of the label bounding box was fixed.

**Comment by pierreporte** [comment]
Just tested again with the latest weekly. The problem is still there. It could be mitigated by fixing #13132.

```
OS: Ubuntu 24.04 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38794 (Git) AppImage
Build type: Release
Branch: main
Hash: a47800d9ccd7d7a7cdb1779d56de03d3c64cd76e
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: French/France (fr_FR)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * CosmeticThread3D
  * Curves 0.6.39
  * CurvedShapes 1.0.9
  * sheetmetal 0.4.19
```

**Comment by FlachyJoe** [comment]
@pierreporte what is your selection pick radius?
![image](https://github.com/user-attachments/assets/19fa2621-dd50-4b76-a414-b4719d396305)

**Comment by pierreporte** [comment]
@FlachyJoe It was 16 px. I don’t remember changing the value. I can select the dimension with 5 px radius. I don’t understand why the lower pick radius solves the problem. The setting doesn’t work for dimensions?

**Comment by FlachyJoe** [comment]
X-axis selector is above the dimension one, it's the problem. 
If your pick radius is greater than the label half size then the axis is shown first.

I'll try to change the selectors order.

**Comment by pierreporte** [comment]
So there is actually no picking radius around label?

@maxwxyz You can close the issue.
