### ISSUE TITLE
Sketcher: dimensional constraint text rendered backwards

### ISSUE THREAD

**Issue by krushia** [FreeCAD/FreeCAD#13852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Seemingly at random, opening a Sketch will show all the constraints backwards (as if seen in a mirror or from behind).
![Screenshot_20240506_001047](https://github.com/FreeCAD/FreeCAD/assets/2147138/9ef16eca-e69e-4851-89f5-39b2864c3b4c)

### Full version info

```shell
OS: Gentoo Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37100 (Git) AppImage
Build type: Release
Branch: main
Hash: ede6c811fd39d68a44949601f2eb7ecc8a67fdb7
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * parts_library
  * Curves 0.6.36
  * A2plus 0.4.64a
  * DynamicData 2.62.0
  * Assembly4 0.50.12 (Disabled)
  * Alternate_OpenSCAD 1.0.0
  * CurvedShapes 1.0.9
  * fasteners 0.5.20
  * SearchBar 1.0.2
  * Nodes 0.1.36 (Disabled)
  * workfeature
  * MnesarcoUtils 0.2.5
  * Manipulator 1.5.7
  * Assembly3 0.12.2
  * lattice2 1.0.0
  * Launcher
  * CommandPanel
  * CubeMenu
  * PieMenu 1.5.0
  * MeshRemodel 1.9.23
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
please provide steps to reproduce or a demo file.

**Comment by krushia** [comment]
[krushia-clampstrip-mkJ-22dev.zip](https://github.com/FreeCAD/FreeCAD/files/15235853/krushia-clampstrip-mkJ-22dev.zip)

Double-click a sketch in the tree. Then double-click a different sketch... keep doing this and eventually the problem arises. I just tried it and it happened on the second opened sketch. Sometimes it takes multiple tries.

**Comment by maxwxyz** [comment]
I can reproduce.
It is correct on opening any of the sketches for the fist time. After opening another one it is flipped.
It does not flip when I actively close the previously opened sketch with the close button in the task dialog. So when I have a sketch open and double click on another sketch, the new one is flipped. 
@PaddleStroke FYI

When looking from the other side I dont see dimensions at all (https://github.com/FreeCAD/FreeCAD/issues/13557) is it the same on your side?

Demo:


https://github.com/FreeCAD/FreeCAD/assets/6246609/60a47bf7-6286-4971-a2ef-eb2c4e320e36



```
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37213 (Git)
Build type: Release
Branch: main
Hash: 20e7deb86a8c6c2cd2378f09f8313760933f3a5c
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * BIM 2021.12.0
  * CfdOF 1.25.11
  * Curves 0.6.36
  * dodo 1.0.1
  * fasteners 0.5.20
  * freecad.gears 1.2.0
  * OpenTheme 2024.5.3
  * OpticsWorkbench 1.0.17
  * sheetmetal 0.4.13
```

**Comment by krushia** [comment]
I can't reproduce #13557. In this case, when viewing from the back side the dimensions are still shown and backwards.

**Comment by maxwxyz** [comment]
It shoukd be fixed now, @krushia please report back

**Comment by krushia** [comment]
Bug still exists, I tried these two versions:

Version: 0.22.0dev.37841 (Git) AppImage
Build type: Release
Branch: main
Hash: 5f761c758e2a0164b00a7183b9c0cbe32688e123


Version: 0.22.0dev.37928 (Git) AppImage
Build type: Release
Branch: main
Hash: e7699b531eba4bee262f7214699f07b96f66ba7b

**Comment by maxwxyz** [comment]
@FlachyJoe any idea about this?

**Comment by krushia** [comment]
This is probably happening because sketches are in a `Part::Mirroring`. Why they sometimes show in reverse and sometimes not is a mystery though. Seems to depend on the order they are opened for editing.

**Comment by krushia** [comment]
Got another example, this time no `Part::Mirroring` (or any other mirroring). Double-clicking `CenterPillarWSnapYZSketch` comes up with reversed dimensions every time. This sketch was showing just fine a few minutes ago...

Also attaching screenshot of history (from Undo button, from the document this thing was created in) since sketch creation. Sadly my console is full of junk from other open documents.

[another-bug-13852-example.FCStd.delete.this.extension.zip](https://github.com/user-attachments/files/16059788/another-bug-13852-example.FCStd.delete.this.extension.zip)

![Screenshot_20240701_190930](https://github.com/FreeCAD/FreeCAD/assets/2147138/7604f21e-8845-4ba6-a8d9-42bdd5bc3b1c)

![Screenshot_20240701_191821](https://github.com/FreeCAD/FreeCAD/assets/2147138/4e9493bf-a3e0-4847-a16c-d9284c61af48)

If someone can tell me how to print undo history in the terminal I can do that.

**Comment by luzpaz** [comment]
@FlachyJoe do you have a moment ?

**Comment by krushia** [comment]
I now have another issue that may be related (evolution of the same cursed project). Now zooming in Sketcher is messed up. Open the file, find a sketch (the one in screenshot is `DualCantileverClipDualClipTemplate`). Now zoom in. The dimension text somehow scales down to nothingness (I thought it never scaled?!?) and the geometry gets "stuck" around where the text vanishes and stops scaling (in screenshot I'm scaled down to nanometers but the display is showing geometry about 15 mm high).

Interestingly, flipping the view around makes the zoom buggy in the other direction I think. IDK I'm very confused...

[krushia-clipstrip-202407311933.FCStd.delete.this.extension.zip](https://github.com/user-attachments/files/16448601/krushia-clipstrip-202407311933.FCStd.delete.this.extension.zip)

![Screenshot_20240731_211725](https://github.com/user-attachments/assets/a8e1b224-fe16-4f8f-89e3-a25638b0033b)

**Comment by krushia** [comment]
While trying to simplify that file, I realized that `Origin002` is tied to both `Part001` and `Body` (which is nested a few fusions deep in `Part001'). This could be the problem.

**Comment by maxwxyz** [comment]
any news on this issue?

**Comment by krushia** [comment]
There is an old report that seems to be the same thing: #6040

I tried two of the files from the forums referenced in that report, and they both have the issue. I suppose that makes this a regression since 19.0? Those files are attached here.

From [toorxBX300_holder.fcstd.delete.this.extension.zip](https://github.com/user-attachments/files/16576282/toorxBX300_holder.fcstd.delete.this.extension.zip) the "Hole Base" sketch:
![Screenshot_20240811_180836](https://github.com/user-attachments/assets/1f48177d-7a2b-42d1-b4b9-d9aaf857e551)



From [sample_to_forum.fcstd.delete.this.extension.zip](https://github.com/user-attachments/files/16576284/sample_to_forum.fcstd.delete.this.extension.zip) the "sketch" sketch:
![Screenshot_20240811_181427](https://github.com/user-attachments/assets/7fdd89e8-3cd0-4ec3-956e-7d32a532699b)

**Comment by luzpaz** [comment]
There are some other mirroring bugs...need to find if they are dupes

**Comment by PaddleStroke** [comment]
https://github.com/user-attachments/assets/be075f46-a08f-4c0d-b9dc-0b0e26a23c0a

It appears the text is flipping when you rotate. Just not at the correct time. See in my video the text flips at some random angle.
So there must be a flaw in the 'angle at which to reverse text' detection.

Also if the substractive loft is deleted this bug doesn't happen anymore in the same sketch.

**Comment by PaddleStroke** [comment]
Some funky stuff is happening in this file. I don't know if it has to do with substractiveloft or if the file is somehow corrupted.

I attached the file to XZ plane. When not in edit mode it looks OK. But then I open edit mode and surprise! It displays on the XY plane

https://github.com/user-attachments/assets/dda705c5-4c8f-40bc-8dd9-750291b04439

**Comment by PaddleStroke** [comment]
Finally I found what's wrong in this files. The sketches are actually not in the body, they are not in the Group property of the body. Which is not normal.

https://github.com/user-attachments/assets/4212decc-1319-49a8-9068-d7b1ca8bf9cb

**Comment by PaddleStroke** [comment]
So this ticket needs to be re-opened, 
https://github.com/FreeCAD/FreeCAD/pull/25478 and https://github.com/FreeCAD/FreeCAD/pull/26033 need to be reversed.
https://github.com/FreeCAD/FreeCAD/issues/26481 will be closed by the reversal.
https://github.com/FreeCAD/FreeCAD/pull/26531 can be closed.

Now the question is what to do about this ticket here. Anyone know how user end up with such documents?

**Comment by PaddleStroke** [comment]
Note, I have analysed the file [toorxBX300_holder.fcstd.delete.this.extension.zip](https://github.com/user-attachments/files/16576282/toorxBX300_holder.fcstd.delete.this.extension.zip).

Which may be a different bug than the other files in this ticket...
However I tested [krushia-clampstrip-mkJ-22dev.zip](https://github.com/FreeCAD/FreeCAD/files/15235853/krushia-clampstrip-mkJ-22dev.zip) and cannot replicate the issue of this file.

**Comment by maxwxyz** [comment]
@ipatch @kadet1090 FYI, do you handle the PRs?

**Comment by PaddleStroke** [comment]
Yes let's @ipatch confirm first. Since there are multiple documents provided maybe I missed something

**Comment by luzpaz** [comment]
> So this ticket needs to be re-opened,

Reopening ticket

**Comment by ipatch** [comment]
yes,  every time i opened the file above, ie. [krushia-clampstrip-mkJ-22dev.zip](https://github.com/FreeCAD/FreeCAD/files/15235853/krushia-clampstrip-mkJ-22dev.zip) the text labels for the constraints were rendering "backwards" / "flipped" without any of the PRs i submitted.

with the current HEAD build

<img width="3323" height="2133" alt="Image" src="https://github.com/user-attachments/assets/5ea69ce9-4dee-42f1-a0f4-2d24351ae9c3" />

**Comment by PaddleStroke** [comment]
Aaah that's it  Ifinally managed to reproduce.
To reproduce you have to double click on a second sketch, **without** closing the first sketch first.

So reproduction steps : 
- Double click AnticlipTemplate 
- Do NOT exit the sketch edit
- Double click ClipArm

So my guess is that by not exiting the sketch edit we are somehow skipping the unsetEdit. Or there is a problem in the order things happen, maybe the setEdit of the second sketch is called before the unsetEdit of the second.

**Comment by kadet1090** [comment]
That could be an option - previews experience similar problems for tasks. If you switch between different tasks without exiting first the unsetEdit is not called and some stuff is left behind.

**Comment by PaddleStroke** [comment]
I'm on it. ParentFinder::findParent is returning false when we switch directly, so it's acting as if there is no parent, hence the wrong placement. Continuing investigation

**Comment by PaddleStroke** [comment]
Ok so the problem appears to be in `ParentFinder::findParentAndSubName`.

It is sometime failing. And when it does the editing placement is not correct.

Why is it failing ? Because `Gui::Selection().getCompleteSelection(ResolveMode::NoResolve);` is not returning what it should be.

After adding some logs I found out several bad behaviors.

1 - The behavior described before (ie switch the sketch edit without leaving the first). In this case the selection object is : 
- Full, ie it has the full path. So this is correct.
- The subname does not point to the correct sketch!! Instead of pointing to the newly selected sketch (Say Sketch001 for example), the subname still show the previous Sketch.
 
2 - After triggering the previous bug several times, I ended up in another bugged situation (where text was also reversed). This time I had exited the previous sketch. Yet upon double click on the next sketch I had : 
- No full path! The sel.pObject was directly the (newly selected at least) sketch and the sel.SubName was empty.

So my new guess is that we are messing up with the selection somewhere by doing a clearSelection or something like this.

**Comment by PaddleStroke** [comment]
Finally I got it!

in unsetEdit we do : 
```
void ViewProviderSketch::unsetEdit(int ModNum)
{
    ...
    // clear the selection and set the new/edited sketch(convenience)
    Gui::Selection().clearSelection();
    Gui::Selection().addSelection(editDocName.c_str(), editObjName.c_str(), editSubName.c_str());
```

This convenience is what is causing the bug. When you double click on a new sketch, it calls resetIfEditing which call the old sketch unsetEdit. This modify the selection by clearing the new sketch and adding the old sketch. Then ParentFinder runs, and obviously cannot find anything since the selection has been changed.
