### ISSUE TITLE
PartDesign: Color settings set back to default on reopening the view settings (dev & RC)

### ISSUE THREAD

**Issue by hawkeyexp** [FreeCAD/FreeCAD#17523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

If a color is set to an object and you reopen the view settings all is set back to default. 

### Full version info

```shell
OS: Windows 11 build 26100
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39024 (Git)
Build type: Release
Branch: main
Hash: cf8ad6637351819dfa07d49cfd65d511fe14a084
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * ArchTextures
  * Behave-Dark-Colors 0.1.1
  * Curves 0.6.48
  * freecad.gears 1.3.0
  * pcb 6.2023.1
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Should be fixed in the weekly already

**Comment by hawkeyexp** [comment]
I'm sorry checked with latest weekly and still present...

OS: Windows 11 build 26100
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39057 (Git)
Build type: Release
Branch: main
Hash: 3be681ef62bf82d32eb1f1935d99e83c48e48da3
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * ArchTextures
  * Behave-Dark-Colors 0.1.1
  * Curves 0.6.48
  * freecad.gears 1.3.0
  * pcb 6.2023.1

**Comment by maxwxyz** [comment]
Can you provide an example file and steps to reproduce? Are you applying colors to bodies, features, parts or selected elements like faces? How is color applied?

**Comment by hawkeyexp** [comment]
I created a short video cause it can be reproduced with a simple object :-)

https://drive.google.com/file/d/1Ou0Mzlh2RfQzQK5bOvS9dCe83ZvyCaek/view?usp=sharing

**Comment by maxwxyz** [comment]
@davesrocketshop FYI

**Comment by davesrocketshop** [comment]
Yup. I can reproduce
