### ISSUE TITLE
Sketcher: Angle rendering broken for negative angles

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#20098]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

![Image](https://github.com/user-attachments/assets/6a17dea1-5b5b-41b4-9ede-653d32c9e0bf)

If you use the arc tool for example. If the angle shown in the OVP is negative, then the rendering of the soDatumLabel is wrong. It was good before : this is a regression of https://github.com/FreeCAD/FreeCAD/pull/17720.

### Full version info

```shell
1.1
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
also related / fixed by https://github.com/FreeCAD/FreeCAD/pull/20101 ?

**Comment by PaddleStroke** [comment]
I don't think so no

**Comment by PaddleStroke** [comment]
unfortunately this issue can be reopened. It appears I have missed that the rendering is still not correct : 

![Image](https://github.com/user-attachments/assets/f49e6a88-5690-4809-8fe4-f2781e584950)

- The arrows are in the wrong direction
- The hole in the middle of the arc is too big.

What it should look like : 

![Image](https://github.com/user-attachments/assets/33dbd90d-11e1-4ef3-ab23-a84b13b7d0ad)

@FlachyJoe could you check it out please?

**Comment by matthiasdanner** [comment]
The wrong arrows are not only on arcs but on every feature where an angle is displayed. For example lines 

<img width="233" alt="Image" src="https://github.com/user-attachments/assets/ca5fee41-d285-4da9-9f33-6118aa4cb93f" />

I created a PR for that
