### ISSUE TITLE
[CAM] [Preferences] Errors generated opening Preferences dialog

### ISSUE THREAD

**Issue by Syres916** [FreeCAD/FreeCAD#22377]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

After updating my self-compiled build and entering `Preferences` for the first time in a few days I receive the following CAM errors/warnings in the Report View:

```
20:21:40  Cannot find icon: preferences-cam
20:21:40  Traceback (most recent call last):
20:21:40    File "/home/username/freecad-daily-build/Mod/CAM/Path/Main/Gui/PreferencesJob.py", line 40, in __init__
    self.form = FreeCADGui.PySideUic.loadUi(":preferences/PathJob.ui")
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
20:21:40    File "<string>", line 4, in <module>
20:21:40  RuntimeError: Cannot open file
20:21:40  Cannot create an instance of "JobPreferencesPage"
20:21:40  JobPreferencesPage is not a preference page
20:21:40  Traceback (most recent call last):
20:21:40    File "/home/username/freecad-daily-build/Mod/CAM/Path/Base/Gui/PreferencesAdvanced.py", line 35, in __init__
    self.form = FreeCADGui.PySideUic.loadUi(":preferences/Advanced.ui")
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
20:21:40    File "<string>", line 4, in <module>
20:21:40  RuntimeError: Cannot open file
20:21:40  Cannot create an instance of "AdvancedPreferencesPage"
20:21:40  AdvancedPreferencesPage is not a preference page
20:21:52  camassets.INFO: CAM asset directory changed in preferences: User parameter:BaseApp/Preferences/Mod/CAM/Tools ToolPath /home/username/.config/FreeCAD/CamAssets
```

### Full version info

```shell
OS: EndeavourOS (X-Cinnamon/cinnamon/xcb)
Architecture: x86_64
Version: 1.1.0dev.42477 (Git)
Build date: 2025/07/05 20:44:22
Build type: Release
Branch: main
Hash: db11f481e9ac74c8f39c513a5cc233058af20fb1
Python 3.13.3, Qt 6.9.0, Coin 4.0.3, Vtk 9.4.2, boost 1_88, Eigen3 3.4.0, PySide 6.9.0
shiboken 6.9.0, SMESH 7.7.1.0, xerces-c 3.3.0, OCC 7.8.1
Locale: English/United Kingdom (en_GB)
Navigation Style/Orbit Style/Rotation Mode: Touchpad/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/95.917/1
Installed mods: 
  * Silk 0.2.0
  * FreeCAD-themes 2025.6.4
  * CfdOF 1.30.4
  * sheetmetal 0.7.23
```

### Subproject(s) affected?

CAM

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
If it's of any use the `CAM` section of my `user.cfg` is:

```
          <FCParamGroup Name="CAM">
            <FCUInt Name="DefaultBBoxNormalColor" Value="1230002175"/>
            <FCUInt Name="DefaultBBoxSelectionColor" Value="210082303"/>
            <FCUInt Name="DefaultHighlightPathColor" Value="4252898303"/>
            <FCUInt Name="DefaultNormalPathColor" Value="798901503"/>
            <FCUInt Name="DefaultPathMarkerColor" Value="798901503"/>
            <FCUInt Name="DefaultProbePathColor" Value="4205839871"/>
            <FCUInt Name="DefaultRapidPathColor" Value="3761320447"/>
            <FCParamGroup Name="Tools">
              <FCText Name="ToolPath">/home/username/.config/FreeCAD/CamAssets</FCText>
            </FCParamGroup>
```

The `CamAssets` folder exists and contain 3 folders `Bit`, `Library` and `Shape`

**Comment by Syres916** [comment]
Also here's the start of the log:

```
20:58:35  OpenGL version is: 4.1 (4.1 (Compatibility Profile) Mesa 25.0.5-arch1.1)
20:58:39  Run Gui init script
20:58:39  Init: Running FreeCADGuiInit.py start script...
20:58:39  Init:   Searching modules...
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/Mesh... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/PartDesign... done
20:58:39  Loading GUI of Start module… done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/Start... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/Draft... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/Sketcher... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/Inspection... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/MeshPart... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/Help... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/Surface... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/Import... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/Idf(InitGui.py not found)... ignore
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/TechDraw... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/Points... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/AddonManager/./... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/Tux... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/Test... done
20:58:39  Loading Material module... done
20:58:39  Module: Part
20:58:39  Loading Part module... done
20:58:39  Loading Measure module... done
20:58:39  Loading GUI of Measure module... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/Measure... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/ReverseEngineering... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/BIM... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/OpenSCAD... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/Plot(InitGui.py not found)... ignore
20:58:39  Loading Path module... done
20:58:39  Loading PathStock... done
20:58:39  Loading Path.Tool.Gui.Controller... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/CAM... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/Show(InitGui.py not found)... ignore
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/Part... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/Web(InitGui.py not found)... ignore
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/Material... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/Robot... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/Spreadsheet... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/Assembly... done
20:58:39  Init:      Initializing /home/username/freecad-daily-build/Mod/Fem... done
20:58:39  Init:      Initializing /home/username/.local/share/FreeCAD/Mod/Silk/./... done
20:58:39  Init:      Packaged workbench Silk workbench specified icon            in class Silk ... replacing with icon from package.xml data.
20:58:39  default matplotlib import
20:58:39  Init:      Initializing /home/username/.local/share/FreeCAD/Mod/CfdOF/./... done
20:58:39  Init:      Packaged workbench  specified icon            in class CfdOFWorkbench ... replacing with icon from package.xml data.
20:58:39  Loading Mesh module... done
20:58:39  Init:      Initializing /home/username/.local/share/FreeCAD/Mod/sheetmetal/./... done
20:58:39  All modules with GUIs using InitGui.py are now initialized
20:58:39  All modules with GUIs initialized using pkgutil are now initialized
20:58:39  Init: Loading FreeCAD GUI
20:58:39  Init: Running FreeCADGuiInit.py start script... done
20:58:42  Init: Activating default workbench PartDesignWorkbench
20:58:42  Loading Sketcher module… done
20:58:42  Loading PartDesign module... done
20:58:42  Loading GUI of Material module... done
20:58:42  Loading GUI of Part module... done
20:58:42  Loading GUI of Sketcher module… done
20:58:42  Loading GUI of PartDesign module... done
20:58:42  Init: Showing main window
20:58:42  Main window restored
20:58:42  Show main window
20:58:42  Toolbars restored
20:58:42  Couldn't connect to spacenav daemon. Please ignore if you don't have a spacemouse.
20:58:42  Init: Entering event loop
20:58:42  Init: Executing event loop...
20:58:42  Init: Processing command line files
```

If I switch to the `CAM` workbench and then open `Preferences`, it opens error/warning free.

**Comment by Syres916** [comment]
FYI @knipknap

**Comment by knipknap** [comment]
@Syres916 I have no idea. Kind of looks like a build problem, I think. Somehow it fails to create the preferences pages from the .ui files?

**Comment by Syres916** [comment]
I use snapshots so I'll go back a couple of weeks and step forward to see if I can get a good git revision and a bad one.

**Comment by Syres916** [comment]
Last good build:

```
OS: EndeavourOS (X-Cinnamon/cinnamon/xcb)
Architecture: x86_64
Version: 1.1.0dev.42338 (Git)
Build date: 2025/06/25 19:40:05
Build type: Release
Branch: main
Hash: 8fe791bd6f11bd22563963035e77012fce41a553
Python 3.13.3, Qt 6.9.0, Coin 4.0.3, Vtk 9.4.2, boost 1_88, Eigen3 3.4.0, PySide 6.9.0
shiboken 6.9.0, SMESH 7.7.1.0, xerces-c 3.3.0, OCC 7.8.1
Locale: English/United Kingdom (en_GB)
Navigation Style/Orbit Style/Rotation Mode: Touchpad/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/95.917/1

```

First bad build:

```
OS: EndeavourOS (X-Cinnamon/cinnamon/xcb)
Architecture: x86_64
Version: 1.1.0dev.42464 (Git)
Build date: 2025/06/30 22:51:46
Build type: Release
Branch: main
Hash: cf082f76422574babc5090fcd8f192da373c9a37
Python 3.13.3, Qt 6.9.0, Coin 4.0.3, Vtk 9.4.2, boost 1_88, Eigen3 3.4.0, PySide 6.9.0
shiboken 6.9.0, SMESH 7.7.1.0, xerces-c 3.3.0, OCC 7.8.1
Locale: English/United Kingdom (en_GB)
Navigation Style/Orbit Style/Rotation Mode: Touchpad/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/95.917/1
```

I carry out the Bisect tomorrow and report back a commit hash.

**Comment by Syres916** [comment]
Errors confirmed by Windows Weekly user, see https://forum.freecad.org/viewtopic.php?t=98187

**Comment by Syres916** [comment]
Git Bisect determined https://github.com/FreeCAD/FreeCAD/commit/b417c5e1803d16c5639bcdf6696bfa71d814f664 to be the cause.

**Comment by Syres916** [comment]
I've started a branch for a Unit Test https://github.com/FreeCAD/FreeCAD/compare/main...Syres916:FreeCAD:Test_Ensure_Preferences_Opens_Error_Free

**Comment by Syres916** [comment]
@knipknap looking at #22196 the only reason this was implemented was due to a handful of users not being able to start FreeCAD while the CI builds and weeklies all worked fine. I've asked for some help to get the Unit Test working as Preferences takes full focus when shown but I'm fairly certain once that Unit Test is working and passes on `Releases/FreeCAD-1-0 branch`, the same test on `main` with have a significant number of the CI tests fail with these errors.

Why don't we back out both #22196 & #21981 and actually get to the root cause of why we are having to treat CAM differently from the other Python Wbs in core, otherwise it feels like we are putting sticking plaster on sticking plaster?

CC @hyarion @sliptonic

**Comment by knipknap** [comment]
@Syres916 I cloned your branch and cannot reproduce the issue.

Given that the root cause fixed by #22196 was based on the (user-specific) loading order I think the most likely outcome of reverting the PRs you referenced is that the problem is shifted to a different group of users; the root cause would not be resolved.

That said:

- Your test branch failed for me as well, but for a different reason: Currently in main the CAM folder is initialized regardless of whether it runs as a test or not. This means that some tests use files from the real user configuration directory instead of a test config and this can fail because it violates the test expectations. I prepared a separate PR for that (#22392).
- Your log looks like perhaps the error handling done in #22196 hides the real problem. I don't normally work with C++, but am wondering if this code is correct:

```
        Py::Module tb(PyImport_ImportModule("traceback"), true);
        if (tb.isNull()) {
            PyErr_SetString(PyExc_ImportError, "Cannot load traceback module");
            return nullptr;
        }
```

Should this:
- check if Python already has an active exception and print it (including a stack trace)?
- Raise the exception such that the message set by PyErr_SetString() is actually made visible?

There is also this error handling, 

```
        if (!filename_obj.isString()) {
            throw Py::Exception();
        }
```

which I am not sure is correct (no error message was set), but is was there already before the PR.

**Comment by Syres916** [comment]
The test branch doesn't work as I stated I have asked for help due to the _Preferences_ dialog taking full focus meaning the Python code won't continue without user interaction. I'll leave the decisions to the maintainers.

@maxwxyz could this please be set to Status: Confirmed as I have replicated the issue using the latest weekly AppImage as well as the Windows user from the forum.

**Comment by furgo16** [comment]
I can confirm this (partly) on my local build. I see this message every time I change any preferences. I do not use the CAM workbench.

```
20:21:52  camassets.INFO: CAM asset directory changed in preferences: User parameter:BaseApp/Preferences/Mod/CAM/Tools ToolPath /home/username/.config/FreeCAD/CamAssets
```
```
OS: Ubuntu 22.04.5 LTS (ubuntu:GNOME/ubuntu/wayland)
Architecture: x86_64
Version: 1.1.0dev.42330 +53 (Git)
Build date: 2025/07/08 20:55:40
Build type: Release
Branch: dxf-new-import-ui-and-more
Hash: e852dc0942de10b5bffbafb86f2004d5980e5bab
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 9.1.0, boost 1_74, Eigen3 3.4.0, PySide 5.15.2
shiboken 5.15.2, SMESH 7.7.1.0, xerces-c 3.2.3, IfcOpenShell 0.8.1.post1, OCC 7.8.1
Navigation Style/Orbit Style/Rotation Mode: Touchpad/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
Logical DPI/Physical DPI/Pixel Ratio: 96/159.34/1
Installed mods: 
  * OpenTheme 2024.9.1
  * fasteners 0.5.38
```

**Comment by knipknap** [comment]
@furgo16 that is expected and not indicative of a bug. Nevertheless: #22392 will silence this unnecessary message.

**Comment by zbynekwinkler** [comment]
I see this error as well (in weekly build appimage). It seems it is looking for this file

https://github.com/FreeCAD/FreeCAD/blob/main/src/Mod/CAM/Gui/Resources/preferences/PathJob.ui

but such file is not bundled inside the appimage.

**Comment by furgo16** [comment]
I can now also confirm the .ui file issue, by simply opening the preferences dialog (no need to navigate to the CAM page):

```
13:35:39  Cannot find icon: preferences-cam
13:35:39  Traceback (most recent call last):
13:35:39    File "/snap/freecad/1569/usr/Mod/CAM/Path/Main/Gui/PreferencesJob.py", line 40, in __init__
13:35:39      self.form = FreeCADGui.PySideUic.loadUi(":preferences/PathJob.ui")
13:35:39    File "<string>", line 4, in <module>
13:35:39  RuntimeError: Cannot open file
13:35:39  JobPreferencesPage is not a preference page
13:35:39  Traceback (most recent call last):
13:35:39    File "/snap/freecad/1569/usr/Mod/CAM/Path/Base/Gui/PreferencesAdvanced.py", line 35, in __init__
13:35:39      self.form = FreeCADGui.PySideUic.loadUi(":preferences/Advanced.ui")
13:35:39    File "<string>", line 4, in <module>
13:35:39  RuntimeError: Cannot open file
13:35:39  AdvancedPreferencesPage is not a preference page
```

```
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu/wayland)
Architecture: x86_64
Version: 1.1.0dev.42543 (Git) Snap 1569
Build date: 2025/07/13 22:47:54
Build type: Release
Branch: main
Hash: 0d71dc5e3248633905f5448d4a22f13a6ba032fc
Python 3.10.12, Qt 5.15.15, Coin 4.0.0, Vtk 9.1.0, boost 1_74, Eigen3 3.4.0, PySide 5.15.11
shiboken 5.15.11, SMESH 7.7.1.0, xerces-c 3.2.3, IfcOpenShell 0.8.2, OCC 7.7.1
Navigation Style/Orbit Style/Rotation Mode: Touchpad/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
Logical DPI/Physical DPI/Pixel Ratio: 96/159.34/1
Installed mods: 
  * Telemetry 1.0.1
  * Assembly4 0.50.17
  * Road 2025.2.22
  * Launcher
```

**Comment by furgo16** [comment]
I've not looked into this, but Is this file perhaps being added to a .qrc file that needs to be updated and committed?

**Comment by jag45** [comment]
I am also getting this error message when I open the preference screen. I have set the CAM workbench to not be loaded, yet as you can see from the screenshot it is 'half' showing in the preferences.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/d773aa33-af89-4dab-a24e-7625f94e100f" />

 If you clear the error message and then load the CAM workbench you don't get the error message when you go into preferences.

Why is it showing in preferences when I deselect it in workbenches? Other workbenches don't do that.

**Comment by jag45** [comment]
Sorry I forgot

OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.42605 (Git)
Build date: 2025/07/18 16:20:04
Build type: Release
Branch: main
Hash: da5e18f5d8e7eb4df89c86c9562599435b5c5187
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.2.5, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United Kingdom (en_GB)
Navigation Style/Orbit Style/Rotation Mode: Gesture/Trackball/Object center
Stylesheet/Theme/QtStyle: MY-Darker-Flat.qss/MY-Darker-Flat/
Logical DPI/Physical DPI/Pixel Ratio: 96/102.299/1
Installed mods: 
  * .pre-commit-config.yaml
  * A2plus 0.4.68
  * Assembly4 0.60.1
  * MY-Darker-Flat
  * package.xml
  * woodworking 1.0.1.39285.1.1.1.2025.07.18

**Comment by chennes** [comment]
If the cause was PR #22196, then this will probably be fixed by https://github.com/FreeCAD/FreeCAD/pull/22697.

**Comment by Syres916** [comment]
I can confirm #22697 fixes this issue, thanks @chennes

**Comment by furgo16** [comment]
It would appear that this issue is not fixed yet: https://github.com/FreeCAD/FreeCAD/issues/22777
