### ISSUE TITLE
Stylesheets: checkbox tick marks are missing (Regression)

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#22478]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

On property editor:
<img width="383" height="70" alt="Image" src="https://github.com/user-attachments/assets/50d6265d-d441-46f8-a618-e596292fa083" />

On preference pages:
<img width="720" height="518" alt="Image" src="https://github.com/user-attachments/assets/9c61a12b-56dd-4cfe-81e8-3c56c3d0e78b" />

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu/wayland)
Architecture: x86_64
Version: 1.1.0dev.42543 (Git) Snap 1569
Build date: 2025/07/13 22:47:54
Build type: Release
Branch: main
Hash: 0d71dc5e3248633905f5448d4a22f13a6ba032fc
Python 3.10.12, Qt 5.15.15, Coin 4.0.0, Vtk 9.1.0, boost 1_74, Eigen3 3.4.0, PySide 5.15.11
shiboken 5.15.11, SMESH 7.7.1.0, xerces-c 3.2.3, IfcOpenShell 0.8.2, OCC 7.7.1
Navigation Style/Orbit Style/Rotation Mode: Touchpad/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
Logical DPI/Physical DPI/Pixel Ratio: 96/159.34/1
Installed mods: 
  * Telemetry 1.0.1
  * Assembly4 0.50.17
  * Road 2025.2.22
  * Launcher
```

### Subproject(s) affected?

None

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Can you test in safe mode?

**Comment by furgo16** [comment]
Good point. I switched to safe mode:

- Selected FreeCAD Light on first run screen
- Arrows and checkbox tick marks are back.

Then I restarted FreeCAD as usual:
- Arrows and checkbox tick marks are back
- I usually use FreeCAD Light, but due to the issues, I tried switching to FreeCAD Dark: the UI remains light, and only the 3D view background switches to dark:

<img width="1848" height="1050" alt="Image" src="https://github.com/user-attachments/assets/092907a9-03c6-408f-9853-3da037e3519d" />

**Comment by furgo16** [comment]
I can reproduce the UI not switching to dark when selecting `FreeCAD Dark`, even in safe mode.

**Comment by maxwxyz** [comment]
Could you try in tomorrows weekly?
@MisterMakerNL was this fixed by the PR?

**Comment by pixelwaster** [comment]
Still missing in 42564. I also do not have the red X to close the 3D window and a couple of other little graphical items.

```
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.42564 (Git)
Build date: 2025/07/14 18:51:42
Build type: Release
Branch: main
Hash: dc2f2374b6ab3e3381653fad125b1b619bb49f7c
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.2.5, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US)
Navigation Style/Orbit Style/Rotation Mode: Touchpad/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/112.198/1
Installed mods: 
  * CurvedShapes 1.0.13
  * Curves 0.6.64
  * FCUpdate
  * FreeCAD-themes 2025.6.4
  * freecad.gears 1.3.0
  * IconThemes
  * ImportNURBS 1.1.0
  * InventorLoader 1.5.1
  * lattice2 1.0.0
  * OpenTheme 2025.5.20
  * Plot 2024.11.26
  * sheetmetal 0.7.24
  * Silk 0.2.0
  * Telemetry 1.0.1
  * Vars 0.0.2.beta1
```

**Comment by obelisk79** [comment]
I'm not sure this is a stylesheet issue. I'm not seeing the compound button arrows in todays build while using OpenTheme.

**Comment by Beep6581** [comment]
Same problem, checkbox and radiobutton states not visible.

- No style sheet: <img width="1380" height="1391" alt="Image" src="https://github.com/user-attachments/assets/f9fa9b8c-7349-40cc-a8d7-b6e96fddbcf8" />
- FreeCAD: <img width="1380" height="1391" alt="Image" src="https://github.com/user-attachments/assets/1f248f29-22b4-40c3-8393-a8b3c5c1600d" />
- FreeCAD Dark: <img width="1380" height="1391" alt="Image" src="https://github.com/user-attachments/assets/9e37d1c7-c72e-42ad-b476-6b73b240170f" />
- FreeCAD Light: <img width="1380" height="1391" alt="Image" src="https://github.com/user-attachments/assets/8730f1aa-4a9e-41ac-bd85-d50a3b320be0" />
- OpenDark: <img width="1380" height="1391" alt="Image" src="https://github.com/user-attachments/assets/98fd387f-8db5-4008-b2a1-94fea1acee47" />

OS: Manjaro Linux (KDE/plasma/xcb)
Architecture: x86_64
Version: 1.1.0dev.42581 (Git)
Build date: 2025/07/16 02:43:57
Build type: Release
Branch: main
Hash: f2d0a69e015f528bba171c3d894445b0177f1b37
Python 3.13.5, Qt 6.9.1, Coin 4.0.3, Vtk 9.5.0, boost 1_88, Eigen3 3.4.0, PySide 6.9.1
shiboken 6.9.1, SMESH 7.7.1.0, xerces-c 3.3.0, OCC 7.9.1
Locale: English/United States (en_US)
Navigation Style/Orbit Style/Rotation Mode: Blender/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: unset/FreeCAD Dark/fusion
Logical DPI/Physical DPI/Pixel Ratio: 96/108.888/1.5
Installed mods: 
  * OpenDark 2023.12.17
  * A2plus 0.4.68
  * fasteners 0.5.38
  * Woodworking 0.21.2.33771
  * CurvedShapes 1.0.13
  * Curves 0.6.60

**Comment by MisterMakerNL** [comment]
@Beep6581 could you try and set a dark theme instead of changing stylesheets.

**Comment by Beep6581** [comment]
@MisterMakerNL Preferences > General > Application > Theme: FreeCAD Dark
With that, checkbox values are displayed correctly.

**Comment by J-Dunn** [comment]
same issue on Fedora 40 with recent AppImages and local master build.

**Comment by MisterMakerNL** [comment]
It probably doesn't load for the new stylesheets because the token for the icons isn't set.
I think we should remove the stylesheet setting, force everyone to make theme's instead of stylesheets.
Which isn't that hard.

**Comment by J-Dunn** [comment]
> It probably doesn't load for the new stylesheets because the token for the icons isn't set. I think we should remove the stylesheet setting, force everyone to make theme's instead of stylesheets. Which isn't that hard.

I don't need themes, I don't want to be "forced" to anything.  I just need need to see checkboxes which work when I start FreeCAD. 

I'm not sure what state the check boxes can get into to not work like this but maybe we just stop messing with "themes" and have a checkbox. 

I have been seeing some odd errors on start up recently , like this:
FreeCAD_weekly-2025.07.14-Linux-x86_64-py311.AppImage

```
23:00:37  During initialization the error "No module named 'AddonCatalog'" occurred in /tmp/.mount_FreeCAhgiFmo/usr/Mod/AddonManager/./InitGui.py
23:00:37  Please look into the log file for further information
23:00:37  Unknown command 'Std_AddonMgr'
23:00:37  Unknown command 'Std_AddonMgr'
23:00:37  Unknown command 'Std_AddonMgr'
23:00:37  Could not create pixmap from qss:images_classic/arrow-down-lightgray.png
23:00:37  Could not create pixmap from qss:images_classic/arrow-down-lightgray.png

```

Maybe this is throwing an exception and the normal initialisations are not completing.

**Comment by MisterMakerNL** [comment]
I don't think you understand the new options you have with the new theme tokens menu. Stylesheets are only needed if you want too drastically change the ui.
You can change the complete look of the ui without needing to open the stylesheet.
https://forum.freecad.org/viewtopic.php?t=98352

I'm going to check if I missed that arrow png.
The new stylesheets are on svg files but that had some issues with the older stylesheets.

**Comment by J-Dunn** [comment]
I don't think you understand I don't care about eye candy. 
I do care if I can't do any work because I cannot see the state of key options needed to configure an operation. 

I guess this also explains why the file Save button is permanently greyed out , even though it still works.

**Comment by MisterMakerNL** [comment]
Changing stylesheets is not a key option there was already a note that it's for advanced users only.
This is because changing the stylesheet only changes part of the UI a lot of colors are set with the theme cfg file. Therefore for any user it has no real use. And if it wasn't there we also wouldn't have this conversation because you wouldn't had any issues.

**Comment by J-Dunn** [comment]
I've never looked at stylesheets, I've never looked at "themes". I don't care how this is done or if it is removed entirely. 

What I do care about is basic functionality so I can use FC to get a job done and a working master branch so the I can work on changes that improve functionality. 

At the moment I can't do either.  Please post when you have this fixed, so that I can update master and restore my local build to a working state instead of messing around with AppImages from May. 

Do you think the File Save button defect is due to this as well ? Or is that a separate bug? That may be older.

**Comment by furgo16** [comment]
@J-Dunn to unblock you, here's a workaround that worked for me, at least on Linux. Two alternative ways to do it:

1. Go to Preferences > General
2. Change theme using the dropdown box. E.g. if you were using FreeCAD Light, change to FreeCAD Dark
3. Press Apply
4. Change back to your original theme
5. Press OK

Alternatively,

1. Go to Help > Restart in Safe Mode
2. When FreeCAD restarts, select a theme
3. Close FreeCAD
4. Now start FreeCAD normally

**Comment by J-Dunn** [comment]
Wow, many thanks, so simple and it worked.  I now have my check boxes working again !! 

Just for the record, the File Save button remains permanently greyed out, though it does work. That must be another issue. I'm guessing the enable icon is in fact the same as the greyed out icon.

**Comment by maxwxyz** [comment]
I was not able to change themes via preferences the first time I loaded yesterdays weekly on my system (the first one with the new themes).
- I had extreme performance issues the first time it opened and did not display new colors. Also, things like the `x` for closing dialogs or tabs were missing.

https://github.com/user-attachments/assets/0dcebe9c-662d-4faa-afaa-693086c5f84f

I then attempted to change themes so the new changes get applied correctly. This was done via preferences. I changed it to light and hit apply. FreeCAD idles for about 5 minutes without response when it crashed:

<img width="2040" height="1294" alt="Image" src="https://github.com/user-attachments/assets/a04104d5-e340-4b8a-bc12-9583514c84f3" />

- On restart, it was using the new light theme and the performance issues were gone. There were still a bunch or errors:

<img width="1762" height="206" alt="Image" src="https://github.com/user-attachments/assets/08d7ee15-8f72-48d0-af5f-e1e0b73bce6b" />

- When I tried to change themes via the start page, even more errors occurred:

<img width="2131" height="1172" alt="Image" src="https://github.com/user-attachments/assets/cf143fb3-9086-41ad-bdd6-90828d3e0a02" />



```
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.1.0dev.42605 (Git)
Build date: 2025/07/18 16:20:04
Build type: Release
Branch: main
Hash: da5e18f5d8e7eb4df89c86c9562599435b5c5187
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.2.5, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: German/Germany (de_DE)
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/133.772/2
Installed mods: 

```

**Comment by MisterMakerNL** [comment]
Maybe we should add the tokens to the classic.cfg file?

**Comment by maxwxyz** [comment]
@furgo16 is this fixed in the weekly?

**Comment by furgo16** [comment]
Thanks for the heads up. Fixed, issue can be closed.
