### ISSUE TITLE
[Issue] ProDark: Light text background colors result in illegible text

### ISSUE THREAD

**Issue by life5ign** [FreeCAD/FreeCAD#8093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=34&t=55134&p=649728#p649728

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Pop!_OS 22.04 LTS (pop:GNOME/pop)
Word size of FreeCAD: 64-bit
Version: 0.20.1.29410 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.20.1)
Hash: f5d13554ecc7a456fb6e970568ae5c74ba727563
Python 3.10.5, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.2
Locale: English/United States (en_US)
Installed mods: 
  * Rocket 2.8.5
  * fasteners 0.4.27
  * Help 1.0.3
  * parts_library
  * lattice2 1.0.0
  * Curves 0.6.5
  * LCInterlocking
  * A2plus 0.4.60g
  * FreeCAD-library-eac93dcfa999af5c1b2682eda999fbac9f4d63df.zip
[/code]
```

### Subproject(s) affected?

None

### Issue description

Excellent theme! I've noticed on my system that certain text, when highlighted, has a white or a yellow background, which, with the white text, makes it illegible:

# Active Part or Body in Combo View tree:

![screenshot_2022-12-26_22-02](https://user-images.githubusercontent.com/63751140/209615274-3943595e-34ee-49f3-8fe3-dbe27c7a3c80.png)

# Annotation in TechDraw:

![screenshot_2022-12-26_22-06](https://user-images.githubusercontent.com/63751140/209615452-7e4373b7-64fa-40f7-a35a-d9bf8c3a3e84.png)

# my system
![screenshot_2022-12-26_22-03](https://user-images.githubusercontent.com/63751140/209615397-a75f032f-d264-43f5-a8a0-851520ab80d3.png)

### Anything else?

I tried resetting all in my Prefereneces, as well as uninstalled all preference packs, restarted freecad, and it didn't fix the issue.  This is how it looks with no style sheet:

![image](https://user-images.githubusercontent.com/63751140/209617100-936a0eac-6e96-4eb5-9d41-3d8559f1d973.png)

![image](https://user-images.githubusercontent.com/63751140/209617119-9de55d95-09a6-4bc3-857b-ba80c0dbbf11.png)

It's a bit of a drag to not be able to read the name of the active part and body; the annotations is a bit less of an annoyance.  Please let me know if there's any other information you need, and thanks for all the work you do to help us build and create.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment]
this is not directly related to stylesheet as it is either hardcoded or a preference, please see https://github.com/FreeCAD/FreeCAD/issues/7623#issuecomment-1287544999
https://forum.freecadweb.org/viewtopic.php?p=635039#p635039
and
https://forum.freecadweb.org/viewtopic.php?f=34&t=70672

**Comment by life5ign** [comment]
Hi, thanks for the reply--I can't believe I didn't find any of those in my google, forum, github searches.  Thanks, looks like the team is aware of it.

**Comment by MisterMakerNL** [comment]
Hey thanks for reporting.
The first issue is fixed in my extremeprodark, but you need too restart Freecad. And apply the preference pack as it's not in the theme file.
The second issue I was sure we fixed it, or looked into it but I can't find where it was discussed.

**Comment by life5ign** [comment]
Thanks!  I just installed extremeprodark (great theme), and the first is definitely fixed, but I still get the issue with annotations in techdraw: 
![image](https://user-images.githubusercontent.com/63751140/209720633-a8458f0b-bbe1-44c1-8bc2-3a50bafc5bb9.png)

**Comment by adrianinsaval** [comment]
yeah that's not themable IIRC, IMO the real issue is that we are using the wrong widget type for this, we are using a text editor to edit a list and adding some workarounds to have line highlight, instead of just using QListWidget that is made for lists and would have highlighting that is themable.

**Comment by WandererFan** [comment]
TechDraw Annotation fixed by PR #8123 / d63ac0f7f6

**Comment by luzpaz** [comment]
Can this be closed ?

**Comment by WandererFan** [comment]
> Can this be closed ?

No.  The PropertyEditor still uses the old QLineEdit based editor for PropertyStringList, which doesn't respect themes.

**Comment by luzpaz** [comment]
@WandererFan should the ticket then be renamed ?

**Comment by WandererFan** [comment]
No need to rename the ticket,  the PropertyEditor has the same illegible text in dark mode.

**Comment by Intuos5** [comment]
There's another window I came across that has inelligible text:
![afbeelding](https://user-images.githubusercontent.com/63149655/214531453-daf5d568-4262-4c17-91be-2d92dd699234.png)
This is in the Dark-Orange stylesheet.

I also modified the Darker-Green stylesheet and had the same issue there:
![afbeelding](https://user-images.githubusercontent.com/63149655/214531923-2851c194-2b3b-4bb6-bb09-fde35075f22e.png)
See: https://forum.freecadweb.org/viewtopic.php?style=2&p=655842#p655842

**Comment by MisterMakerNL** [comment]
All of these are pretty much fixed by now. Although some are a bit of a workaround like adding 
```
          <FCParamGroup Name="Spreadsheet">
            <FCText Name="AliasedCellBackgroundColor">#9b4de6</FCText>
          </FCParamGroup>

```
Too the Stylesheet CFG file.
Techdraw dev did a great job on fixing it on his part!
![afbeelding](https://user-images.githubusercontent.com/29804962/222550932-8f0ff0ef-b3f8-4ce9-9ca4-1e50a92b6d9d.png)
Can go further in how to fix all the old style-sheets.... here https://github.com/FreeCAD/FreeCAD/issues/7623

**Comment by luzpaz** [comment]
bumping for status

**Comment by MisterMakerNL** [comment]
Pro dark has been removed from main to the theme, repro. 
This can be moved or closed, for the other theme's we have other topics.

**Comment by luzpaz** [comment]
>> Can this be closed ?

> No.  The PropertyEditor still uses the old QLineEdit based editor for PropertyStringList, which doesn't respect themes. 

@WandererFan checking in

**Comment by obelisk79** [comment]
@maxwxyz this should either be moved to the FreeCAD-themes repo or closed.
