### ISSUE TITLE
[Problem] Zooming in 3D view causes substantial decrease in frame rate

### ISSUE THREAD

**Issue by dominikh** [FreeCAD/FreeCAD#9544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: NixOS 23.05 (Stoat)
Word size of FreeCAD: 64-bit
Version: 0.21.0.Unknown
Build type: Release
Python 3.10.11, Qt 5.15.9, Coin 4.0.1, Vtk 9.2.6, OCC 7.6.2
Locale: English/United States (en_US)
Installed mods: 
  * fasteners 0.4.56
  * ProDarkThemePreferencePack 1.0.0
[/code]
```

### Subproject(s) affected?

Core

### Problem description

When zooming in and out, the frame drops from 60 fps (my display's refresh rate) to roughly 30 fps, as determined by the frame counter overlay of FreeCAD. This is independent of the complexity of the scene.

This isn't really noticeable when zooming with a mouse wheel, but it is highly noticeable when using a Space Mouse, where most movement will contain some amount of zoom, and where the unstable frame rate leads to a choppy experience.

### Anything else?

My hypothesis is that the slowdown is caused by updating the dimensions in the bottom right corner of the main window. To test this, I've patched FreeCAD to remove said updates, and this solved the issue.

```
diff --git i/src/Gui/MainWindow.cpp w/src/Gui/MainWindow.cpp
index 1cb9a32475..86c17ef3e7 100644
--- i/src/Gui/MainWindow.cpp
+++ w/src/Gui/MainWindow.cpp
@@ -2165,7 +2165,7 @@ void MainWindow::setPaneText(int i, QString text)
         showStatus(MainWindow::Pane, text);
     }
     else if (i==2) {
-        d->sizeLabel->setText(text);
+        // d->sizeLabel->setText(text);
     }
 }
```

I know that both UI layout and text rendering can be expensive, but missing the 16.6 ms target is still surprising to me.

A similar issue occurs when moving the mouse over objects, which updates the "preselected" information in the bottom left of the main window. This, however, is less of an issue with the Space Mouse, albeit still problematic when using the Space Mouse and the normal mouse simultaneously, e.g. when making edits.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xtemp09** [comment]
Most likely the culprit is copying QString. Perhaps, standard `const QString &` is better.

**Comment by xtemp09** [comment]
I cannot reproduce this slowdown on Windows 10.

<details><summary>Windows 10 build 19044</summary>

```ruby
OS: Windows 10 build 19044
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34594 (Git)
Build type: Release
Branch: master
Hash: e9187412d9b3b372ee4c1d7e2fc7a0bf08a2e647
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Russian/Russia (ru_RU)
```
</details>

I cannot reproduce the slowdown on Ubuntu 22.04 with this line commented or without.

<details><summary>Ubuntu 22.04.3 LTS</summary>

```ruby
OS: Ubuntu 22.04.3 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34667 (Git)
Build type: Debug
Branch: main
Hash: af5b8714a8371162addb97dd25c29250fcecf7ad
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.1
Locale: Russian/Russia (ru_RU)
```

</details>

The problem can be caused by the Space Mouse or its code in FreeCAD.

**Comment by xtemp09** [comment]
@dominikh, if you replace

```cpp
void MainWindow::setPaneText(int i, QString text)
```

with

```cpp
void MainWindow::setPaneText(int i, const QString &text)
```

do you notice the slowdown? Of course, one needs to change the declaration of the function too in https://github.com/FreeCAD/FreeCAD/blob/3b0720c2b2e8233701a74ac72d211a19e825e909/src/Gui/MainWindow.h#L220

**Comment by dominikh** [comment]
> The problem can be caused by the Space Mouse or its code in FreeCAD.

Note that the Space Mouse only makes it easier to notice the problem. I can reproduce it with just a normal mouse wheel, without a Space Mouse even connected to the system. Zooming by scrolling in/out rapidly is limited to 30 fps while the sizeLabel gets updated. When zoomed in so far that the label reads "0.00 mm x 0.00 mm", further zooming does happen at 60 fps. 

> void MainWindow::setPaneText(int i, const QString &text)

The proposed change made no difference.

**Comment by xtemp09** [comment]
@dominikh, I pushed the commit xtemp09/FreeCAD@5acec63ee639b55e874067832725ff10cd721e67 into the branch [gui-fix4](https://github.com/xtemp09/FreeCAD/tree/gui-fix4).

Could you compile and check if it fixes the problem? To git clone it, one has to do:

```ruby
git clone -b gui-fix4 --filter=blob:none https://github.com/xtemp09/FreeCAD.git
```

**Comment by luzpaz** [comment]
@OficineRobotica is this ticket still valid ? Looking at your screencasts don't show this issue AFAICT

**Comment by Ely31** [comment]
This is still an issue

OS: KDE neon 6.3 (KDE/plasmax11/xcb)
Architecture: x86_64
Version: 1.1.0dev.40845 (Git)
Build date: 2025/03/18 14:59:22
Build type: Unknown
Branch: main
Hash: c1ada6bc4070df7804ccea69773b0cfa0d8226fd
Python 3.12.3, Qt 5.15.16, Coin 4.0.2, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/Qt default
Logical DPI/Physical DPI/Pixel Ratio: 96/141.585/1
Installed mods: 
  * IconThemes
  * fasteners 0.5.37
  * sheetmetal 0.7.22
  * freecad.gears 1.3.0
  * OpenTheme 2024.9.1

**Comment by bombela** [comment]
1.1.0dev 42006. Windows 10. Nvidia 3070 RTX. 20 FPS when zooming. It stutters, and it feels laggy. Otherwise I can spin around at 120pfs (the monitor refresh rate).

**Comment by Ely31** [comment]
Keep it open, built a few days ago and still the same ~20fps when zooming.

**Comment by xtemp09** [comment]
@Ely31, could you provide _About_ info?

**Comment by Ely31** [comment]
OS: KDE neon User Edition (KDE/plasmax11/xcb)
Architecture: x86_64
Version: 1.1.0dev.42787 (Git)
Build date: 2025/07/29 18:49:41
Build type: Unknown
Branch: main
Hash: bc207c0a077e6db166cf36033ccf72042a85216f
Python 3.12.3, Qt 6.9.1, Coin 4.0.2, Vtk 9.1.0, boost 1_83, Eigen3 3.4.0, PySide 6.9.1
shiboken 6.9.1, SMESH 7.7.1.0, xerces-c 3.2.4, OCC 7.6.3
Locale: English/United States (en_US)
Navigation Style/Orbit Style/Rotation Mode: SolidWorks/Free Turntable/Drag at cursor
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/
Logical DPI/Physical DPI/Pixel Ratio: 96/141.585/1
Installed mods: 
  * IconThemes
  * fasteners 0.5.37
  * sheetmetal 0.7.22
  * freecad.gears 1.3.0
  * OpenTheme 2024.9.1

**Comment by xtemp09** [comment]
@Ely31, do you zoom with the mouse wheel or a Space Mouse? Does navigation style affect the decrease?









----









> Build type: Unknown

Is it a release or debug build?

**Comment by Ely31** [comment]
It doesn't matter if you use a space mouse or a regular mouse wheel. The issue is much more prominent with a space mouse however because it's practically impossible to not input some zoom movement while using it. Here's a video with the fps counter in freecad enabled, panning and orbiting with mouse are smooth, zooming with mouse wheel is terrible, and using the spacemouse at the end is the same lag as the mouse wheel.

https://github.com/user-attachments/assets/cd59b018-6637-4ffe-8c4c-391502eedc00

**Comment by bombela** [comment]
Same issue here. Though mainline lags so much compared to
linkstage3-stable, the zoom issue is not the biggest of my problem.

I am using the scroll wheel on the mouse. It drops in fps when zooming.

ls3 is butter smooth at 120fps for me.

What about the mouse polling rate? or the monitor refresh rate? Maybe some
bad interaction?

My monitor is 120hz, 4k, 10bit. Mouse is 1kHz polling

**Comment by softsteel** [comment]
FreeCAD 1.0.2 OpenDark.

The render time is fixed at 1ms, yet I get sporadic dips down to 20FPS while zooming. Rotating is reasonably smooth in comparison.
 
I did a quick ETW trace and found FreeCAD was cumulatively allocating 1.5G over 3s of scrolling in and out on a mousepad. The choppiness probably has something to do with that.

<img width="987" height="247" alt="Image" src="https://github.com/user-attachments/assets/973bf092-ddf0-47f7-b4ce-7a86dff58d4f" />

**Comment by xtemp09** [comment]
When zooming with the mouse wheel, I see some drop of FPS. I cannot reproduce this memory allocation.






```ruby
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.0.2.39319 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.2)
Hash: 256fc7eff3379911ab5daf88e10182c509aa8052
Python 3.11.13, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: Russian/Russia (ru_RU)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
```

**Comment by ma00aem** [comment]
Hi i have also noticed this. But it seams to be better with perspective than Isometric?

**Comment by FEA-eng** [comment]
Can someone confirm if this issue is still relevant?

**Comment by ma00aem** [comment]
Hi. i tested the 1.1 (not weekly) version yesterday and it had the same or even worse fram drops. If i orbit with mouse i get consistant frame rate. The isometric view and the zoom have heavy stutter. If i change to perspective it works great. Se attached video

https://youtu.be/7A8YLogtsH8

same behavior in 1.2.0 dev 2026 04 08

**Comment by luzpaz** [comment]
@ma00aem can you please test on 1.2-dev ?

**Comment by ma00aem** [comment]
I have now tested on FreeCAD_weekly-2026.04.22-Linux-x86_64.AppImage and it hast the same problem . I'm unfortunatly a rookie here on Linux, so i need good instructions to know if and how i can contribute. I'm on fedora 43 and have tried with amd, geforce and Intel graphic cards. Same behavior

**Comment by christianglodt** [comment]
I've taken a look with sysprof, however I don't have a debug build or anything as I'm not a FreeCAD developer. I profiled for 15 seconds while zooming in and out in FreeCAD 1.1.1 (installed using FlatPak, however I get the slowdown also with the AppImage).

<img width="2554" height="1844" alt="Image" src="https://github.com/user-attachments/assets/b0d3cc83-55b8-449e-85c9-f66a05c7b7f4" />

The flamegraph shows a lot of time spent doing QImage::detachv, which is a method that is used to make a non-shared copy of a QImage. The method appears in 23.290 samples (corresponding to 59%), which seems like a lot.

For comparison purposes, here is a flamegraph of 15 seconds of just orbiting in the 3D view without zooming:

<img width="2560" height="1836" alt="Image" src="https://github.com/user-attachments/assets/4abb6d4f-5883-4522-99ae-c4be0dd27d3a" />

The QImage::detachv calls are much less numerous and time-consuming: only 420 samples corresponding to 1.75%.

Maybe a developer can use breakpoints or something to investigate the root cause of these QImages detaching when zooming.

**Comment by christianglodt** [comment]
I also found that turning off the status bar fixes the slowdown. It really seems like some component updates much too eagerly when the 3D viewport changes zoom/fov.
